# de


env:
  DB_PASSWORD: root

#action 이름
name: dev-deploy

#action trigger develop, prod를 제외한 나머지 브랜치에 대해서 푸시되면 동작하도록 한다.
on:
  push:
    #대상 브랜치
    branches: [ develop ]

#실행단위 - 메소드같은 애
jobs:
  #job이름
  dev-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

    # 각종 변수들 셋팅하는 곳
      - name: set env
        id: set-envs
        run: |
          if [ $GITHUB_REF_NAME = 'develop' ]; then
            PROFILE=dev
          else
            PROFILE=dev
          fi
          
          HWAMOK_ZIP=hwamok-$PROFILE-$(date +'%Y%m%dT%H%M%S%Z')
          
          echo "HWAMOK_ZIP : $HWAMOK_ZIP"
          echo "PROFILE: $PROFILE"
  
          echo "::set-output name=PROFILE::$(echo $PROFILE)"
          echo "::set-output name=HWAMOK_ZIP::$(echo HWAMOK_ZIP)"

      # ubuntu에 기본으로 깔려있는 mysql 시작
      - name: Set up MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE hwamok-test;' -uroot -proot

      # jdk 17 세팅
      - name: Set up JDK 17
        uses: actions/setup-java@main
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      # gradlew 권한 추가
      - name: Run chmod to make gradlew executable
        run: chmod +x ./gradlew

      # gradle test 실행 문서화시 밑에 넣어줘야함
      - name: Integration Test
        uses: gradle/gradle-build-action@main
        with:
          gradle-version: wrapper
          arguments: test


      # Elastic Beanstalk으로 배포를 할 예정 => zip 파일을 넣음
      # EB는 paas => Platform as a Service => 장점 관리를 안해도 된다.
      # .zip 파일을  올려야 한다  .ebextention(optional) Procfile .platform 우리의 jar 파일
      # Saas => Service as a Service, 대부분 회사들이 이걸 사용함, 우리 회사 서비스를 다른 회사에 서비스에 연결

      # .ebextention(optional) => eb의 초기 설정값을 넣어줌, 서버 타임존을 넣어줌
      # Server Timezone => 전세계 공통 시간 UTC(default), 한국 시간 KST(UTC + 9) 00 자정 -> 15시
      # 00.{이름}.config => 01-{이름}.config
      # procfiles/Procfile => 실제 우리 jar파일 실행하는 명령어가 들어가 있음
      # java -jar {name}.jar
      # .platform -nginx서버 설정
      # 서버의 맥스 용량, body의 용량

      # s3로 zip 파일 업로드
      # aws cli 명령어를 통해서 s3에 올린
      # zip 파일을 eb환경으로 업데이트

      - name: move zip
        run: |
          mv build/distributions/hwamok.zip build/distributions/${{ steps.set-envs.outputs.HWAMOK_ZIP }}

      - name: upload to s3
        run: |
          aws s3 cp build/distributions/${{ steps.set-envs.outputs.HWAMOK_ZIP }} s3://elasticbeanstalk-ap-northeast-2-897907197066

      - name: Api Deploy To Dev Server
        if: steps.set-envs.outputs.PROFILE == 'dev'
        run: |
          aws elasticbeanstalk create-application-version --application-name dev-hwamok \
              --version-label ${{ steps.set-envs.outputs.HWAMOK_ZIP }} --source-bundle S3Bucket="elasticbeanstalk-ap-northeast-2-897907197066",S3Key="${{ steps.set-envs.outputs.HWAMOK_ZIP }}" \
              --region=ap-northeast-2

          aws elasticbeanstalk update-environment --application-name dev-hwamok \
              --environment-name dev-hwamok-env --version-label ${{ steps.set-envs.outputs.HWAMOK_ZIP }}